service:
  name: authService

frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'stage'}
  region: ${opt:region, 'sa-east-1'}
  memorySize: 128
  timeout: 10
  logRetentionInDays: 14
  deploymentBucket: serverlessdeployment-${self:provider.region}
  environment:
    stage: ${self:provider.region}
    region: ${self:provider.region}
  #role: // TODO define a role for this service
  #awsKmsKeyArn // TODO define a sns for the dead letter

package:
  excludeDevDependencies: false

custom:
  customDomain:
    domainName: ${self:provider.stage}.gs.ai-td.com
    basePath: api
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: regional

functions:
  getBearer:
    handler: src/authenticator/handler.getBearer
    description: function responsible for authentication
    events:
      - http:
          path: auth/getBearer
          method: post